clear;clc
% Impulse Response of Bi-quad
fs = 48000;
dt = 1/fs;
t = 0:dt:1-dt;

impulso = zeros(48000,1);
impulso(1) = 1;

% EXAMPLE 1: Equalize an audio signal
    frameLength = 512;
    reader = dsp.AudioFileReader( ...
               'Filename','RockDrums-48-stereo-11secs.mp3', ...
               'SamplesPerFrame',frameLength);

    player = audioDeviceWriter('SampleRate',reader.SampleRate);
    % 3-band Equalizer with additional shelving filters
    MPE = multibandParametricEQ(...
                     'NumEQBands',1, ...
                     'Frequencies',410, ...
                     'QualityFactors',0.66, ...
                     'PeakGains',-2.4, ...
                     ...
                     'HasHighpassFilter',true,...
                     'HighpassCutoff',95,...
                     'HighpassSlope',10,...
                     ...
                     'HasHighShelfFilter',true, ...
                     'HighShelfCutoff',8800, ...
                     'HighShelfSlope',0.45, ...
                     'HighShelfGain',3.2, ...
                     ...
                     'SampleRate',reader.SampleRate);

y = MPE(impulso);
H = fft(y);   
f = 0:1:fs-1;

figure(2)
semilogx(f, 20*log10(abs(H)));
grid on
axis([20 20000 -20 15])
title('Respuesta en frecuencia del filtro')

help multibandParametricEQ
